/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspensionRouteImport } from './routes/suspension'
import { Route as GearboxRouteImport } from './routes/gearbox'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as IndexRouteImport } from './routes/index'

const SuspensionRoute = SuspensionRouteImport.update({
  id: '/suspension',
  path: '/suspension',
  getParentRoute: () => rootRouteImport,
} as any)
const GearboxRoute = GearboxRouteImport.update({
  id: '/gearbox',
  path: '/gearbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/gearbox': typeof GearboxRoute
  '/suspension': typeof SuspensionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/gearbox': typeof GearboxRoute
  '/suspension': typeof SuspensionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/gearbox': typeof GearboxRoute
  '/suspension': typeof SuspensionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/database' | '/gearbox' | '/suspension'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/database' | '/gearbox' | '/suspension'
  id: '__root__' | '/' | '/database' | '/gearbox' | '/suspension'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseRoute: typeof DatabaseRoute
  GearboxRoute: typeof GearboxRoute
  SuspensionRoute: typeof SuspensionRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/suspension': {
      id: '/suspension'
      path: '/suspension'
      fullPath: '/suspension'
      preLoaderRoute: typeof SuspensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gearbox': {
      id: '/gearbox'
      path: '/gearbox'
      fullPath: '/gearbox'
      preLoaderRoute: typeof GearboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseRoute: DatabaseRoute,
  GearboxRoute: GearboxRoute,
  SuspensionRoute: SuspensionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
