/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspensionRouteImport } from './routes/suspension'
import { Route as GearboxRouteImport } from './routes/gearbox'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AlignmentRouteImport } from './routes/alignment'
import { Route as AeroRouteImport } from './routes/aero'
import { Route as IndexRouteImport } from './routes/index'

const SuspensionRoute = SuspensionRouteImport.update({
  id: '/suspension',
  path: '/suspension',
  getParentRoute: () => rootRouteImport,
} as any)
const GearboxRoute = GearboxRouteImport.update({
  id: '/gearbox',
  path: '/gearbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignmentRoute = AlignmentRouteImport.update({
  id: '/alignment',
  path: '/alignment',
  getParentRoute: () => rootRouteImport,
} as any)
const AeroRoute = AeroRouteImport.update({
  id: '/aero',
  path: '/aero',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aero': typeof AeroRoute
  '/alignment': typeof AlignmentRoute
  '/chat': typeof ChatRoute
  '/database': typeof DatabaseRoute
  '/gearbox': typeof GearboxRoute
  '/suspension': typeof SuspensionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aero': typeof AeroRoute
  '/alignment': typeof AlignmentRoute
  '/chat': typeof ChatRoute
  '/database': typeof DatabaseRoute
  '/gearbox': typeof GearboxRoute
  '/suspension': typeof SuspensionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aero': typeof AeroRoute
  '/alignment': typeof AlignmentRoute
  '/chat': typeof ChatRoute
  '/database': typeof DatabaseRoute
  '/gearbox': typeof GearboxRoute
  '/suspension': typeof SuspensionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aero'
    | '/alignment'
    | '/chat'
    | '/database'
    | '/gearbox'
    | '/suspension'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aero'
    | '/alignment'
    | '/chat'
    | '/database'
    | '/gearbox'
    | '/suspension'
  id:
    | '__root__'
    | '/'
    | '/aero'
    | '/alignment'
    | '/chat'
    | '/database'
    | '/gearbox'
    | '/suspension'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AeroRoute: typeof AeroRoute
  AlignmentRoute: typeof AlignmentRoute
  ChatRoute: typeof ChatRoute
  DatabaseRoute: typeof DatabaseRoute
  GearboxRoute: typeof GearboxRoute
  SuspensionRoute: typeof SuspensionRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/suspension': {
      id: '/suspension'
      path: '/suspension'
      fullPath: '/suspension'
      preLoaderRoute: typeof SuspensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gearbox': {
      id: '/gearbox'
      path: '/gearbox'
      fullPath: '/gearbox'
      preLoaderRoute: typeof GearboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alignment': {
      id: '/alignment'
      path: '/alignment'
      fullPath: '/alignment'
      preLoaderRoute: typeof AlignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aero': {
      id: '/aero'
      path: '/aero'
      fullPath: '/aero'
      preLoaderRoute: typeof AeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AeroRoute: AeroRoute,
  AlignmentRoute: AlignmentRoute,
  ChatRoute: ChatRoute,
  DatabaseRoute: DatabaseRoute,
  GearboxRoute: GearboxRoute,
  SuspensionRoute: SuspensionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
